services:
  ffc-sfd-customer-receiver-preferences:
    build:
      context: .
      target: production
    image: ffc-sfd-customer-receiver-preferences
    container_name: ffc-sfd-customer-receiver-preferences
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-sfd-customer-receiver-preferences-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      MESSAGE_HOST: ${MESSAGE_HOST}
      MESSAGE_USER: ${MESSAGE_USER}
      MESSAGE_PASSWORD: ${MESSAGE_PASSWORD}
      PREFERENCES_SUBSCRIPTION_ADDRESS: ${PREFERENCES_SUBSCRIPTION_ADDRESS}-${DEV_SUFFIX}
      PREFERENCES_TOPIC_ADDRESS: ${PREFERENCES_TOPIC_ADDRESS}-${DEV_SUFFIX}
      COSMOS_ENDPOINT: ${COSMOS_ENDPOINT:-https://cosmos-db:8081}
      COSMOS_KEY: ${COSMOS_KEY}
      COSMOS_PREFERENCES_DATABASE: ${COSMOS_PREFERENCES_DATABASE:-ffc-sfd-customer-receiver-preferences}
      COSMOS_PREFERENCES_CONTAINER: ${COSMOS_PREFERENCES_CONTAINER:-preferences-container}
