services:
  ffc-sfd-customer-receiver-preferences:
    build:
      context: .
      target: production
    image: ffc-sfd-customer-receiver-preferences
    container_name: ffc-sfd-customer-receiver-preferences
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-sfd-customer-receiver-preferences-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
