- key: APPINSIGHTS_CONNECTIONSTRING
  value: "{{servicename}}-APPINSIGHTS-CONNECTIONSTRING"
  type: "keyvault"
- key: MESSAGE_HOST
  value: "SNDADPINFSB4401.servicebus.windows.net"
- key: PREFERENCES_TOPIC_ADDRESS
  value: "fcp-sfd-customer-preferences"
- key: PREFERENCES_SUBSCRIPTION_ADDRESS
  value: "fcp-sfd-customer-receiver-preferences"
- key: COSMOS_ENDPOINT
  value: "https://fcp-sfd-temp-cosmos.documents.azure.com:443/"